# Generated by Django 4.0 on 2022-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, null=True)),
                ('commissions', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('sku', models.CharField(max_length=200, null=True)),
                ('stock', models.CharField(max_length=200, null=True)),
                ('ratings', models.CharField(max_length=200, null=True)),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('shop_name', models.CharField(max_length=200, null=True)),
                ('item_price', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
