# Generated by Django 3.2.7 on 2022-04-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscrapedata',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userscrapedata',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
