# Generated by Django 3.2.7 on 2022-05-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHT', '0002_auto_20220411_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarazAllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.CharField(max_length=200, null=True)),
                ('product_title', models.CharField(max_length=200, null=True)),
                ('product_price', models.CharField(max_length=200, null=True)),
                ('product_review', models.CharField(max_length=200, null=True)),
                ('product_rating', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
