# Generated by Django 3.2.7 on 2022-05-17 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PHT', '0004_darazalldata_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=200, null=True)),
                ('product_url', models.CharField(max_length=200, null=True)),
                ('product_title', models.CharField(max_length=200, null=True)),
                ('product_price', models.CharField(max_length=200, null=True)),
                ('product_review', models.CharField(max_length=200, null=True)),
                ('product_rating', models.CharField(max_length=200, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PHT.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='DarazAllData',
        ),
        migrations.AddField(
            model_name='userscrapedata',
            name='done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
