# Generated by Django 3.2.7 on 2022-05-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHT', '0005_auto_20220517_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryrecords',
            name='category_id',
        ),
        migrations.AddField(
            model_name='categoryrecords',
            name='category_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
