# Generated by Django 3.2.7 on 2022-05-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHT', '0009_competitordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitordata',
            name='search_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='competitordata',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
